/**
 * Provenance construction from a validated verification chain: the typed
 * actor -> activity -> entity story of the chain, expressed in the
 * @epoch/provenance PROV-DM-adapted model (R5/R17 — provenance is
 * first-class).
 *
 * Mapping (deterministic):
 * - Agents: run executors and approval approvers (with their recorded PROV
 *   kinds; the chain validator already rejects one actor carrying two
 *   kinds).
 * - Activities: each run becomes a `verification-run`/`validation-run`
 *   activity (the stage distinction stays visible in provenance); each
 *   approval becomes an `approval` activity at its decision time.
 * - Entities: requirements, claims, methods, and results as typed
 *   entities; every evidence record becomes a content-addressed entity
 *   carrying its canonical digest.
 * - Statements: methods derive from their claims; claims derive from their
 *   requirements; runs are associated with their executors and use their
 *   methods; evidence is generated by its run; results are generated by
 *   their run (at decision time) and derived from the evidence they
 *   consumed; approvals are associated with their approvers and use the
 *   results they judged.
 */
import { computeEvidenceDigest } from '@epoch/evidence';
import type {
  ProvenanceActivity,
  ProvenanceAgent,
  ProvenanceEntity,
  ProvenanceGraph,
  ProvenanceStatement,
} from '@epoch/provenance';
import { validateProvenanceGraph } from '@epoch/provenance';
import { admitChain } from './validate';
import type { ChainIssue, VerificationChain } from './types';

/** Outcome of provenance construction. */
export type ChainProvenanceResult =
  | { ok: true; graph: ProvenanceGraph }
  | { ok: false; issues: readonly ChainIssue[] };

function buildProvenance(chain: VerificationChain): ProvenanceGraph {
  const agents = new Map<string, ProvenanceAgent>();
  const activities: ProvenanceActivity[] = [];
  const entities: ProvenanceEntity[] = [];
  const statements: ProvenanceStatement[] = [];

  // Agents: executors and approvers.
  for (const run of chain.runs) {
    agents.set(run.executedBy, { agentId: run.executedBy, agentKind: run.executedByKind });
  }
  for (const approval of chain.approvals) {
    agents.set(approval.approverId, { agentId: approval.approverId, agentKind: approval.approverKind });
  }

  // Entities: requirements, claims, methods, evidence (content-addressed), results.
  for (const requirement of chain.requirements) {
    entities.push({ entityId: `requirement:${requirement.requirementId}`, entityKind: 'requirement' });
  }
  for (const claim of chain.claims) {
    entities.push({ entityId: `claim:${claim.claimId}`, entityKind: 'claim' });
  }
  for (const method of chain.methods) {
    entities.push({ entityId: `method:${method.methodId}`, entityKind: 'method' });
  }
  const seenEvidence = new Set<string>();
  for (const record of chain.evidence) {
    const digest = computeEvidenceDigest(record);
    if (seenEvidence.has(digest)) continue;
    seenEvidence.add(digest);
    entities.push({ entityId: `evidence:${digest}`, entityKind: 'evidence', digest });
  }
  for (const result of chain.results) {
    entities.push({ entityId: `result:${result.resultId}`, entityKind: 'result' });
  }

  // Claims derive from requirements; methods derive from claims.
  for (const claim of chain.claims) {
    statements.push({
      relation: 'was-derived-from',
      generatedEntityId: `claim:${claim.claimId}`,
      usedEntityId: `requirement:${claim.requirementId}`,
    });
  }
  for (const method of chain.methods) {
    statements.push({
      relation: 'was-derived-from',
      generatedEntityId: `method:${method.methodId}`,
      usedEntityId: `claim:${method.claimId}`,
    });
  }

  // Runs: associated with their executor, using their method, generating
  // their evidence.
  for (const run of chain.runs) {
    const activityId = `run:${run.runId}`;
    activities.push({
      activityId,
      activityKind: run.stage === 'verification' ? 'verification-run' : 'validation-run',
      startedAt: run.startedAt,
      endedAt: run.endedAt,
    });
    statements.push({
      relation: 'was-associated-with',
      activityId,
      agentId: run.executedBy,
      role: 'executor',
    });
    statements.push({
      relation: 'used',
      activityId,
      entityId: `method:${run.methodId}`,
      role: 'method',
    });
    for (const digest of run.producedEvidence) {
      if (!seenEvidence.has(digest)) continue; // chain validation already rejected this case
      statements.push({
        relation: 'was-generated-by',
        entityId: `evidence:${digest}`,
        activityId,
        role: 'evidence',
      });
    }
  }

  // Results: generated by their run at decision time, derived from the
  // evidence they consumed.
  for (const result of chain.results) {
    statements.push({
      relation: 'was-generated-by',
      entityId: `result:${result.resultId}`,
      activityId: `run:${result.runId}`,
      time: result.decidedAt,
      role: 'result',
    });
    for (const digest of result.evidenceDigests) {
      statements.push({
        relation: 'was-derived-from',
        generatedEntityId: `result:${result.resultId}`,
        usedEntityId: `evidence:${digest}`,
      });
    }
  }

  // Approvals: activities associated with their approver, using the result.
  for (const approval of chain.approvals) {
    const activityId = `approval:${approval.approvalId}`;
    activities.push({
      activityId,
      activityKind: 'approval',
      startedAt: approval.decidedAt,
      endedAt: approval.decidedAt,
    });
    statements.push({
      relation: 'was-associated-with',
      activityId,
      agentId: approval.approverId,
      role: 'approver',
    });
    statements.push({
      relation: 'used',
      activityId,
      entityId: `result:${approval.resultId}`,
      role: 'approved-result',
    });
  }

  return {
    schemaVersion: 1,
    agents: [...agents.values()],
    activities,
    entities,
    statements,
  };
}

/**
 * Build the PROV-style provenance graph of a verification chain. The input
 * is admitted first (parse + semantic validation); an invalid chain has no
 * provenance. The constructed graph is itself validated before being
 * returned (defense in depth — unreachable by construction).
 */
export function chainProvenance(input: unknown): ChainProvenanceResult {
  const admitted = admitChain(input);
  if (!admitted.ok) return { ok: false, issues: admitted.issues };
  const graph = buildProvenance(admitted.chain);
  const validation = validateProvenanceGraph(graph);
  if (!validation.ok) {
    return {
      ok: false,
      issues: [
        {
          code: 'provenance-invalid',
          message: `internal: constructed provenance graph failed validation (${validation.issues[0]?.message ?? 'invalid'})`,
          details: validation.issues,
        },
      ],
    };
  }
  return { ok: true, graph };
}
