#!/usr/bin/env node
// W058 — the local link state of the Three.js renderer adapter package.
//
// adapters/renderers/threejs is a NESTED package path that the frozen
// pnpm-workspace.yaml glob ("adapters/*" — one level) does not match, so
// the package is NOT a pnpm workspace project until the Tech Lead's
// registration pass adds the glob entry (the PR #124 / W056-lockfile-
// reconcile precedent; raised as an advisory on the W058 PR). Until then,
// this script builds the package's gitignored LOCAL node_modules so
// typecheck/lint/test run exactly as they will post-registration:
//
//   - @epoch/* workspace packages  -> symlinks to ../../../packages/<pkg>
//     (each resolves its own dependencies through its own real node_modules);
//   - vitest / eslint / typescript / @types/node -> symlinks into
//     @epoch/renderer-fabric's node_modules (the same pinned catalog
//     versions every package uses);
//   - three + @types/three -> staged from the pnpm registry at EXACTLY the
//     versions pinned in the root catalog (read from pnpm-workspace.yaml at
//     run time — NO version literals are committed anywhere in this tree;
//     the staging manifest is generated and gitignored).
//
// The committed package.json declares `three: "catalog:"` /
// `@types/three: "catalog:"` per the dependency-baseline policy; it becomes
// installable verbatim the moment the workspace glob covers this path.
//
// Idempotent; safe to re-run. When the package IS registered (a pnpm
// node_modules with .modules.yaml appears), the script exits without
// touching it. Nothing here is ever committed (outputs are gitignored).

import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const pkgDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const rootDir = path.resolve(pkgDir, '..', '..', '..');
const localModules = path.join(pkgDir, 'node_modules');
const stageDir = path.join(pkgDir, '.local-stage');

const log = (msg) => console.log(`[link-local] ${msg}`);

// Already a real pnpm-installed package (post-registration)? Never touch it.
if (fs.existsSync(path.join(localModules, '.modules.yaml'))) {
  log('pnpm-managed node_modules present (package registered) — nothing to do.');
  process.exit(0);
}

// --- read the catalog pins from the root workspace manifest (no literals here).
const workspaceYaml = fs.readFileSync(path.join(rootDir, 'pnpm-workspace.yaml'), 'utf8');
const catalogPin = (name) => {
  const escaped = name.replace(/[/@]/g, (c) => `\\${c}`);
  const re = new RegExp(`^\\s+(?:"${name}"|'${name}'|${escaped}):\\s*"?([^"\\s]+)"?\\s*$`, 'm');
  const m = workspaceYaml.match(re);
  if (!m) throw new Error(`catalog pin for "${name}" not found in pnpm-workspace.yaml`);
  return m[1];
};
const THREE_PIN = catalogPin('three');
const THREE_TYPES_PIN = catalogPin('@types/three');
log(`catalog pins: three@${THREE_PIN}, @types/three@${THREE_TYPES_PIN}`);

// --- stage the engine at the catalog pins (generated, gitignored manifest).
fs.rmSync(stageDir, { recursive: true, force: true });
fs.mkdirSync(stageDir, { recursive: true });
const stageManifest = {
  name: 'epoch-adapter-renderer-threejs-local-stage',
  private: true,
  description:
    'GITIGNORED local staging of the catalog-pinned three.js engine for the pre-registration verification of @epoch/adapter-renderer-threejs. Generated by scripts/link-local.mjs; never committed.',
  dependencies: { three: THREE_PIN, '@types/three': THREE_TYPES_PIN },
};
fs.writeFileSync(path.join(stageDir, 'package.json'), `${JSON.stringify(stageManifest, null, 2)}\n`);
const env = { ...process.env, COREPACK_ENABLE_DOWNLOAD_PROMPT: '0' };
try {
  execFileSync('pnpm', ['install', '--dir', stageDir, '--ignore-workspace', '--no-frozen-lockfile', '--silent'], {
    stdio: 'inherit',
    env,
  });
} catch {
  // Fallback: corepack pnpm (the documented invocation when pnpm is not on PATH).
  execFileSync('corepack', ['pnpm', 'install', '--dir', stageDir, '--ignore-workspace', '--no-frozen-lockfile'], {
    stdio: 'inherit',
    env,
  });
}

// --- workspace packages + toolchain this package needs locally.
const fabricModules = path.join(rootDir, 'packages', 'renderer-fabric', 'node_modules');
const packages = [
  'agent-protocol',
  'capability-registry',
  'eslint-config',
  'experience-protocol',
  'renderer-fabric',
  'renderer-runtime',
  'tsconfig',
  'world-experience',
];

// --- build the local node_modules.
fs.rmSync(localModules, { recursive: true, force: true });
fs.mkdirSync(path.join(localModules, '@epoch'), { recursive: true });
fs.mkdirSync(path.join(localModules, '@types'), { recursive: true });
fs.mkdirSync(path.join(localModules, '.bin'), { recursive: true });

const symlink = (from, to) => fs.symlinkSync(path.relative(path.dirname(to), from), to, 'junction');
for (const name of packages) {
  symlink(path.join(rootDir, 'packages', name), path.join(localModules, '@epoch', name));
}
// The engine + its types, staged at the catalog pins.
symlink(path.join(stageDir, 'node_modules', 'three'), path.join(localModules, 'three'));
symlink(path.join(stageDir, 'node_modules', '@types', 'three'), path.join(localModules, '@types', 'three'));
// The shared toolchain (the same pinned versions the fabric package uses).
symlink(path.join(fabricModules, 'vitest'), path.join(localModules, 'vitest'));
symlink(path.join(fabricModules, 'eslint'), path.join(localModules, 'eslint'));
symlink(path.join(fabricModules, 'typescript'), path.join(localModules, 'typescript'));
symlink(path.join(fabricModules, '@types', 'node'), path.join(localModules, '@types', 'node'));
if (fs.existsSync(path.join(fabricModules, '@types', 'espree'))) {
  symlink(path.join(fabricModules, '@types', 'espree'), path.join(localModules, '@types', 'espree'));
}
// Executables: tsc / vitest / eslint (the fabric's .bin entries point at
// the shared pnpm store — symlinking them keeps resolution intact).
for (const bin of ['tsc', 'tsserver', 'vitest', 'eslint']) {
  const target = path.join(fabricModules, '.bin', bin);
  if (fs.existsSync(target)) {
    fs.symlinkSync(
      path.relative(path.join(localModules, '.bin'), target),
      path.join(localModules, '.bin', bin),
      'junction',
    );
  }
}
// A self-link so the qa/renderer-conformance/threejs battery can import the
// adapter by package name pre-registration (pnpm provides it post-registration).
symlink(pkgDir, path.join(localModules, '@epoch', 'adapter-renderer-threejs'));

// --- the conformance battery needs the same chain.
const qaThreeDir = path.join(rootDir, 'qa', 'renderer-conformance', 'threejs');
if (fs.existsSync(qaThreeDir)) {
  const qaLink = path.join(qaThreeDir, 'node_modules');
  fs.rmSync(qaLink, { recursive: true, force: true });
  symlink(localModules, qaLink);
  log('linked qa/renderer-conformance/threejs/node_modules');
}

log('local node_modules ready (gitignored; catalog-pinned three staged).');
