/**
 * @epoch/construction-world-fixture — the semantic entity set (W071, ACR-012).
 *
 * Every construction system of the ACR-012 scene tree is present as an
 * Epoch semantic entity: SITE (boundary, access, staging, excavation),
 * FOUNDATION (strip foundation, foundation bases, ground slab),
 * STRUCTURE (columns, beams, roof structure), ENVELOPE (walls, doors,
 * windows, roof), MEP (electrical, lighting, plumbing, HVAC, drainage),
 * FINISHES (ceiling, floor, paint, fixtures). Each entity carries BOTH:
 *   - the renderer-neutral geometry (position / bbox / rotation /
 *     primitive / layer / phase / visibleByDefault) — the W061 fixture-
 *     owned projection data;
 *   - the engineering projection (entityId / entityType / label /
 *     material+grade / dimensions / quantity+unit / phase / status /
 *     cost reference / constraints) — the ACR-012 §4 fields, the
 *     inspector projection of the same world.
 *
 * Realistic counts (dozens, not hundreds): 4 columns, 2 beams, 4 walls,
 * 1 door + 2 windows, ≥1 element per MEP subsystem. The hidden legacy
 * conduit is the deliberate MEP clash risk (findable only by isolating/
 * revealing the MEP layer — the spatial-world acceptance).
 */
import type { Vec3, Quaternion } from '@epoch/experience-protocol';
import type {
  ConstructionEntityGeometry,
  ConstructionEntityProjection,
} from './types';
import { ENTITY_IDS } from './version';

/** The identity quaternion (no rotation). */
const IDENTITY_QUATERNION: Quaternion = { x: 0, y: 0, z: 0, w: 1 } as unknown as Quaternion;

// Vec3 + Quaternion literal helpers — keep the entity table terse.
const v = (x: number, y: number, z: number): Vec3 => [x, y, z] as unknown as Vec3;
const q = (x: number, y: number, z: number, w: number): Quaternion =>
  ({ x, y, z, w }) as unknown as Quaternion;
const qY = (degY: number): Quaternion => {
  // Y-axis rotation only (radians) — common construction rotations.
  const r = (degY * Math.PI) / 180;
  const s = Math.sin(r / 2);
  const c = Math.cos(r / 2);
  return { x: 0, y: s, z: 0, w: c } as unknown as Quaternion;
};

// ---------------------------------------------------------------------------
// The renderer-neutral geometry (per entity). Positions in meters; the
// building footprint is 8m × 6m, the lot is 20m × 12m. Y=0 is ground.
// ---------------------------------------------------------------------------

export const ENTITY_GEOMETRY: readonly ConstructionEntityGeometry[] = [
  // ---- SITE ------------------------------------------------------------
  {
    entityId: ENTITY_IDS.siteBoundary,
    primitive: 'box',
    position: v(0, 0.6, 0),
    bbox: v(20, 1.2, 12),
    rotation: IDENTITY_QUATERNION,
    layer: 'lyr-site',
    phase: 'phase-site',
    visibleByDefault: true,
  },
  {
    entityId: ENTITY_IDS.siteAccess,
    primitive: 'box',
    position: v(0, 0, -6),
    bbox: v(4, 1.5, 0.4),
    rotation: IDENTITY_QUATERNION,
    layer: 'lyr-site',
    phase: 'phase-site',
    visibleByDefault: true,
  },
  {
    entityId: ENTITY_IDS.siteStaging,
    primitive: 'plane',
    position: v(-15, 0.01, -8),
    bbox: v(6, 0.02, 4),
    rotation: IDENTITY_QUATERNION,
    layer: 'lyr-site',
    phase: 'phase-site',
    visibleByDefault: true,
  },
  {
    entityId: ENTITY_IDS.siteExcavation,
    primitive: 'box',
    position: v(0, -1, 0),
    bbox: v(8.4, 1.0, 6.4),
    rotation: IDENTITY_QUATERNION,
    layer: 'lyr-site',
    phase: 'phase-excavation',
    visibleByDefault: true,
  },

  // ---- FOUNDATION ------------------------------------------------------
  {
    entityId: ENTITY_IDS.foundationStrip,
    primitive: 'box',
    position: v(0, -0.6, 0),
    bbox: v(8.4, 0.8, 6.4),
    rotation: IDENTITY_QUATERNION,
    layer: 'lyr-foundation',
    phase: 'phase-foundation',
    visibleByDefault: true,
  },
  {
    entityId: ENTITY_IDS.foundationBaseA,
    primitive: 'box',
    position: v(-4, -0.5, -3),
    bbox: v(1.2, 0.6, 1.2),
    rotation: IDENTITY_QUATERNION,
    layer: 'lyr-foundation',
    phase: 'phase-foundation',
    visibleByDefault: true,
  },
  {
    entityId: ENTITY_IDS.foundationBaseB,
    primitive: 'box',
    position: v(4, -0.5, 3),
    bbox: v(1.2, 0.6, 1.2),
    rotation: IDENTITY_QUATERNION,
    layer: 'lyr-foundation',
    phase: 'phase-foundation',
    visibleByDefault: true,
  },
  {
    entityId: ENTITY_IDS.groundSlab,
    primitive: 'plane',
    position: v(0, 0.05, 0),
    bbox: v(8, 0.1, 6),
    rotation: IDENTITY_QUATERNION,
    layer: 'lyr-foundation',
    phase: 'phase-foundation',
    visibleByDefault: true,
  },

  // ---- STRUCTURE ------------------------------------------------------
  {
    entityId: ENTITY_IDS.column01,
    primitive: 'box',
    position: v(-4, 1.5, -3),
    bbox: v(0.3, 3.0, 0.3),
    rotation: IDENTITY_QUATERNION,
    layer: 'lyr-structure',
    phase: 'phase-structure',
    visibleByDefault: true,
  },
  {
    entityId: ENTITY_IDS.column02,
    primitive: 'box',
    position: v(4, 1.5, -3),
    bbox: v(0.3, 3.0, 0.3),
    rotation: IDENTITY_QUATERNION,
    layer: 'lyr-structure',
    phase: 'phase-structure',
    visibleByDefault: true,
  },
  {
    entityId: ENTITY_IDS.column03,
    primitive: 'box',
    position: v(-4, 1.5, 3),
    bbox: v(0.3, 3.0, 0.3),
    rotation: IDENTITY_QUATERNION,
    layer: 'lyr-structure',
    phase: 'phase-structure',
    visibleByDefault: true,
  },
  {
    entityId: ENTITY_IDS.column04,
    primitive: 'box',
    position: v(4, 1.5, 3),
    bbox: v(0.3, 3.0, 0.3),
    rotation: IDENTITY_QUATERNION,
    layer: 'lyr-structure',
    phase: 'phase-structure',
    visibleByDefault: true,
  },
  {
    entityId: ENTITY_IDS.beam01,
    primitive: 'box',
    position: v(0, 3.0, -3),
    bbox: v(8.0, 0.3, 0.3),
    rotation: IDENTITY_QUATERNION,
    layer: 'lyr-structure',
    phase: 'phase-structure',
    visibleByDefault: true,
  },
  {
    entityId: ENTITY_IDS.beam02,
    primitive: 'box',
    position: v(0, 3.0, 3),
    bbox: v(8.0, 0.3, 0.3),
    rotation: IDENTITY_QUATERNION,
    layer: 'lyr-structure',
    phase: 'phase-structure',
    visibleByDefault: true,
  },
  {
    entityId: ENTITY_IDS.roofStructure,
    primitive: 'box',
    position: v(0, 3.4, 0),
    bbox: v(8.4, 0.2, 6.4),
    rotation: IDENTITY_QUATERNION,
    layer: 'lyr-structure',
    phase: 'phase-roof',
    visibleByDefault: true,
  },

  // ---- ENVELOPE -------------------------------------------------------
  {
    entityId: ENTITY_IDS.wallNorth,
    primitive: 'box',
    position: v(0, 1.5, -3),
    bbox: v(8.0, 3.0, 0.2),
    rotation: IDENTITY_QUATERNION,
    layer: 'lyr-envelope',
    phase: 'phase-walls',
    visibleByDefault: true,
  },
  {
    entityId: ENTITY_IDS.wallSouth,
    primitive: 'box',
    position: v(0, 1.5, 3),
    bbox: v(8.0, 3.0, 0.2),
    rotation: IDENTITY_QUATERNION,
    layer: 'lyr-envelope',
    phase: 'phase-walls',
    visibleByDefault: true,
  },
  {
    entityId: ENTITY_IDS.wallEast,
    primitive: 'box',
    position: v(4, 1.5, 0),
    bbox: v(0.2, 3.0, 6.0),
    rotation: IDENTITY_QUATERNION,
    layer: 'lyr-envelope',
    phase: 'phase-walls',
    visibleByDefault: true,
  },
  {
    entityId: ENTITY_IDS.wallWest,
    primitive: 'box',
    position: v(-4, 1.5, 0),
    bbox: v(0.2, 3.0, 6.0),
    rotation: IDENTITY_QUATERNION,
    layer: 'lyr-envelope',
    phase: 'phase-walls',
    visibleByDefault: true,
  },
  {
    entityId: ENTITY_IDS.doorFront,
    primitive: 'box',
    position: v(0, 1.0, 3),
    bbox: v(1.0, 2.0, 0.25),
    rotation: IDENTITY_QUATERNION,
    layer: 'lyr-envelope',
    phase: 'phase-walls',
    visibleByDefault: true,
  },
  {
    entityId: ENTITY_IDS.windowSouth01,
    primitive: 'box',
    position: v(-2.5, 1.5, 3),
    bbox: v(1.2, 1.2, 0.05),
    rotation: IDENTITY_QUATERNION,
    layer: 'lyr-envelope',
    phase: 'phase-walls',
    visibleByDefault: true,
  },
  {
    entityId: ENTITY_IDS.windowSouth02,
    primitive: 'box',
    position: v(2.5, 1.5, 3),
    bbox: v(1.2, 1.2, 0.05),
    rotation: IDENTITY_QUATERNION,
    layer: 'lyr-envelope',
    phase: 'phase-walls',
    visibleByDefault: true,
  },
  {
    entityId: ENTITY_IDS.roofCladding,
    primitive: 'box',
    position: v(0, 3.6, 0),
    bbox: v(8.6, 0.05, 6.6),
    rotation: qY(0),
    layer: 'lyr-envelope',
    phase: 'phase-roof',
    visibleByDefault: true,
  },

  // ---- MEP ------------------------------------------------------------
  {
    entityId: ENTITY_IDS.electricalPanel,
    primitive: 'box',
    position: v(-3.8, 1.5, -2.8),
    bbox: v(0.8, 1.2, 0.2),
    rotation: IDENTITY_QUATERNION,
    layer: 'lyr-mep',
    phase: 'phase-mep',
    visibleByDefault: true,
  },
  {
    entityId: ENTITY_IDS.lightingCircuit,
    primitive: 'cylinder',
    position: v(-2, 2.95, 0),
    bbox: v(0.05, 4.0, 0.05),
    rotation: q(1, 0, 0, 0),
    layer: 'lyr-mep',
    phase: 'phase-mep',
    visibleByDefault: true,
  },
  {
    entityId: ENTITY_IDS.plumbingRiser,
    primitive: 'cylinder',
    position: v(2, 1.5, 0),
    bbox: v(0.08, 3.0, 0.08),
    rotation: q(1, 0, 0, 0),
    layer: 'lyr-mep',
    phase: 'phase-mep',
    visibleByDefault: true,
  },
  {
    entityId: ENTITY_IDS.hvacDuct,
    primitive: 'box',
    position: v(2, 2.9, 0),
    bbox: v(4.0, 0.25, 0.25),
    rotation: IDENTITY_QUATERNION,
    layer: 'lyr-mep',
    phase: 'phase-mep',
    visibleByDefault: true,
  },
  {
    entityId: ENTITY_IDS.hvacUnit,
    primitive: 'box',
    position: v(-2, 3.7, 0),
    bbox: v(1.5, 0.6, 1.0),
    rotation: IDENTITY_QUATERNION,
    layer: 'lyr-mep',
    phase: 'phase-mep',
    visibleByDefault: true,
  },
  {
    entityId: ENTITY_IDS.drainagePipe,
    primitive: 'cylinder',
    position: v(0, -0.15, 0),
    bbox: v(0.1, 8.0, 0.1),
    rotation: q(0, 0, 1, 0),
    layer: 'lyr-mep',
    phase: 'phase-mep',
    visibleByDefault: true,
  },
  {
    // The hidden MEP clash risk: the legacy conduit the HVAC duct route
    // crosses. Invisible until the user REVEALS/isolates the MEP layer —
    // the spatial-world acceptance: the clash is found IN the world.
    entityId: ENTITY_IDS.legacyConduit,
    primitive: 'cylinder',
    position: v(2, 2.9, 0.3),
    bbox: v(0.05, 4.0, 0.05),
    rotation: q(1, 0, 0, 0),
    layer: 'lyr-mep',
    phase: 'phase-mep',
    visibleByDefault: false,
  },

  // ---- FINISHES ------------------------------------------------------
  {
    entityId: ENTITY_IDS.ceiling,
    primitive: 'plane',
    position: v(0, 3.0, 0),
    bbox: v(8.0, 0.05, 6.0),
    rotation: IDENTITY_QUATERNION,
    layer: 'lyr-finishes',
    phase: 'phase-finishes',
    visibleByDefault: true,
  },
  {
    entityId: ENTITY_IDS.floor,
    primitive: 'plane',
    position: v(0, 0.1, 0),
    bbox: v(8.0, 0.05, 6.0),
    rotation: IDENTITY_QUATERNION,
    layer: 'lyr-finishes',
    phase: 'phase-finishes',
    visibleByDefault: true,
  },
  {
    entityId: ENTITY_IDS.paintWall,
    primitive: 'box',
    position: v(0, 1.5, 0),
    bbox: v(8.0, 2.4, 0.02),
    rotation: IDENTITY_QUATERNION,
    layer: 'lyr-finishes',
    phase: 'phase-finishes',
    visibleByDefault: true,
  },
  {
    entityId: ENTITY_IDS.fixtures,
    primitive: 'box',
    position: v(0, 2.9, 0),
    bbox: v(2.0, 0.15, 0.5),
    rotation: IDENTITY_QUATERNION,
    layer: 'lyr-finishes',
    phase: 'phase-finishes',
    visibleByDefault: true,
  },
];

// ---------------------------------------------------------------------------
// The engineering projection (per entity — ACR-012 §4 fields).
// ---------------------------------------------------------------------------

export const ENTITY_PROJECTIONS: readonly ConstructionEntityProjection[] = [
  // SITE
  {
    entityId: ENTITY_IDS.siteBoundary,
    entityType: 'site:boundary',
    label: 'Site boundary fence',
    material: { name: 'Galvanised chain-link', grade: '2.4m height' },
    dimensions: v(20, 1.2, 12),
    quantity: { value: '64.0', unit: 'm' },
    phase: 'phase-site',
    status: 'complete',
    cost: { lineId: 'line:cs-site-boundary', currency: 'EUR', amount: '12800.00' },
    constraints: ['Site secure before excavation'],
  },
  {
    entityId: ENTITY_IDS.siteAccess,
    entityType: 'site:access',
    label: 'North site access gate',
    material: { name: 'Steel gate', grade: 'S275' },
    dimensions: v(4, 1.5, 0.4),
    quantity: { value: '1', unit: 'nr' },
    phase: 'phase-site',
    status: 'complete',
    cost: { lineId: 'line:cs-site-access', currency: 'EUR', amount: '1850.00' },
    constraints: ['Vehicle access maintained throughout'],
  },
  {
    entityId: ENTITY_IDS.siteStaging,
    entityType: 'site:staging',
    label: 'Staging / laydown yard',
    material: { name: 'Crushed aggregate', grade: 'Type 1 50mm' },
    dimensions: v(6, 0.02, 4),
    quantity: { value: '24.0', unit: 'm2' },
    phase: 'phase-site',
    status: 'complete',
    cost: { lineId: 'line:cs-site-staging', currency: 'EUR', amount: '720.00' },
    constraints: ['Material delivery capacity 24m2'],
  },
  {
    entityId: ENTITY_IDS.siteExcavation,
    entityType: 'site:excavation',
    label: 'Excavation pit',
    material: { name: 'Open cut excavation', grade: '1:1 batter' },
    dimensions: v(8.4, 1.0, 6.4),
    quantity: { value: '53.76', unit: 'm3' },
    phase: 'phase-excavation',
    status: 'complete',
    cost: { lineId: 'line:cs-site-excavation', currency: 'EUR', amount: '2688.00' },
    constraints: ['Spoil removed off-site'],
  },
  // FOUNDATION
  {
    entityId: ENTITY_IDS.foundationStrip,
    entityType: 'foundation:strip',
    label: 'Perimeter strip foundation',
    material: { name: 'RC strip footing', grade: 'C25/30' },
    dimensions: v(8.4, 0.8, 6.4),
    quantity: { value: '11.76', unit: 'm3' },
    phase: 'phase-foundation',
    status: 'complete',
    cost: { lineId: 'line:cs-foundation-strip', currency: 'EUR', amount: '1411.20' },
    constraints: ['Concrete cured 28 days before loading'],
  },
  {
    entityId: ENTITY_IDS.foundationBaseA,
    entityType: 'foundation:base',
    label: 'Pad base A (column COL-01)',
    material: { name: 'RC pad base', grade: 'C30/37' },
    dimensions: v(1.2, 0.6, 1.2),
    quantity: { value: '0.86', unit: 'm3' },
    phase: 'phase-foundation',
    status: 'complete',
    cost: { lineId: 'line:cs-foundation-base-a', currency: 'EUR', amount: '129.00' },
    constraints: ['Bearing capacity 200 kPa'],
  },
  {
    entityId: ENTITY_IDS.foundationBaseB,
    entityType: 'foundation:base',
    label: 'Pad base B (column COL-04)',
    material: { name: 'RC pad base', grade: 'C30/37' },
    dimensions: v(1.2, 0.6, 1.2),
    quantity: { value: '0.86', unit: 'm3' },
    phase: 'phase-foundation',
    status: 'complete',
    cost: { lineId: 'line:cs-foundation-base-b', currency: 'EUR', amount: '129.00' },
    constraints: ['Bearing capacity 200 kPa'],
  },
  {
    entityId: ENTITY_IDS.groundSlab,
    entityType: 'foundation:slab',
    label: 'Ground floor slab',
    material: { name: 'RC ground slab', grade: 'C28/35 + mesh' },
    dimensions: v(8, 0.1, 6),
    quantity: { value: '4.80', unit: 'm3' },
    phase: 'phase-foundation',
    status: 'complete',
    cost: { lineId: 'line:cs-ground-slab', currency: 'EUR', amount: '720.00' },
    constraints: ['DPM below slab; power-floated finish'],
  },
  // STRUCTURE
  {
    entityId: ENTITY_IDS.column01,
    entityType: 'structure:column',
    label: 'Column COL-01 (NW)',
    material: { name: 'RC column', grade: 'C40/50' },
    dimensions: v(0.3, 3.0, 0.3),
    quantity: { value: '0.27', unit: 'm3' },
    phase: 'phase-structure',
    status: 'complete',
    cost: { lineId: 'line:cs-column-01', currency: 'EUR', amount: '54.00' },
    constraints: ['4nr 16mm rebar; axial 280 kN'],
  },
  {
    entityId: ENTITY_IDS.column02,
    entityType: 'structure:column',
    label: 'Column COL-02 (NE)',
    material: { name: 'RC column', grade: 'C40/50' },
    dimensions: v(0.3, 3.0, 0.3),
    quantity: { value: '0.27', unit: 'm3' },
    phase: 'phase-structure',
    status: 'complete',
    cost: { lineId: 'line:cs-column-02', currency: 'EUR', amount: '54.00' },
    constraints: ['4nr 16mm rebar; axial 280 kN'],
  },
  {
    entityId: ENTITY_IDS.column03,
    entityType: 'structure:column',
    label: 'Column COL-03 (SW)',
    material: { name: 'RC column', grade: 'C40/50' },
    dimensions: v(0.3, 3.0, 0.3),
    quantity: { value: '0.27', unit: 'm3' },
    phase: 'phase-structure',
    status: 'complete',
    cost: { lineId: 'line:cs-column-03', currency: 'EUR', amount: '54.00' },
    constraints: ['4nr 16mm rebar; axial 280 kN'],
  },
  {
    entityId: ENTITY_IDS.column04,
    entityType: 'structure:column',
    label: 'Column COL-04 (SE)',
    material: { name: 'RC column', grade: 'C40/50' },
    dimensions: v(0.3, 3.0, 0.3),
    quantity: { value: '0.27', unit: 'm3' },
    phase: 'phase-structure',
    status: 'complete',
    cost: { lineId: 'line:cs-column-04', currency: 'EUR', amount: '54.00' },
    constraints: ['4nr 16mm rebar; axial 280 kN'],
  },
  {
    entityId: ENTITY_IDS.beam01,
    entityType: 'structure:beam',
    label: 'Beam grid B1 (north span)',
    material: { name: 'RC beam', grade: 'C40/50' },
    dimensions: v(8.0, 0.3, 0.3),
    quantity: { value: '0.72', unit: 'm3' },
    phase: 'phase-structure',
    status: 'complete',
    cost: { lineId: 'line:cs-beam-01', currency: 'EUR', amount: '144.00' },
    constraints: ['Bearing 150mm at columns; 2nr 20mm rebar'],
  },
  {
    entityId: ENTITY_IDS.beam02,
    entityType: 'structure:beam',
    label: 'Beam grid B2 (south span)',
    material: { name: 'RC beam', grade: 'C40/50' },
    dimensions: v(8.0, 0.3, 0.3),
    quantity: { value: '0.72', unit: 'm3' },
    phase: 'phase-structure',
    status: 'complete',
    cost: { lineId: 'line:cs-beam-02', currency: 'EUR', amount: '144.00' },
    constraints: ['Bearing 150mm at columns; 2nr 20mm rebar'],
  },
  {
    entityId: ENTITY_IDS.roofStructure,
    entityType: 'structure:roof',
    label: 'Roof structure (flat slab)',
    material: { name: 'RC flat roof slab', grade: 'C32/40' },
    dimensions: v(8.4, 0.2, 6.4),
    quantity: { value: '10.75', unit: 'm3' },
    phase: 'phase-roof',
    status: 'complete',
    cost: { lineId: 'line:cs-roof-structure', currency: 'EUR', amount: '2150.00' },
    constraints: ['Fall 1:80 to rainwater outlets'],
  },
  // ENVELOPE
  {
    entityId: ENTITY_IDS.wallNorth,
    entityType: 'envelope:wall',
    label: 'North wall',
    material: { name: 'AAC blockwork', grade: '200mm' },
    dimensions: v(8.0, 3.0, 0.2),
    quantity: { value: '24.0', unit: 'm2' },
    phase: 'phase-walls',
    status: 'complete',
    cost: { lineId: 'line:cs-wall-north', currency: 'EUR', amount: '1920.00' },
    constraints: ['U-value 0.22 W/m2K'],
  },
  {
    entityId: ENTITY_IDS.wallSouth,
    entityType: 'envelope:wall',
    label: 'South wall (with door + windows)',
    material: { name: 'AAC blockwork', grade: '200mm' },
    dimensions: v(8.0, 3.0, 0.2),
    quantity: { value: '18.56', unit: 'm2' },
    phase: 'phase-walls',
    status: 'complete',
    cost: { lineId: 'line:cs-wall-south', currency: 'EUR', amount: '1484.80' },
    constraints: ['Net of door + window openings'],
  },
  {
    entityId: ENTITY_IDS.wallEast,
    entityType: 'envelope:wall',
    label: 'East wall',
    material: { name: 'AAC blockwork', grade: '200mm' },
    dimensions: v(0.2, 3.0, 6.0),
    quantity: { value: '18.0', unit: 'm2' },
    phase: 'phase-walls',
    status: 'complete',
    cost: { lineId: 'line:cs-wall-east', currency: 'EUR', amount: '1440.00' },
    constraints: ['U-value 0.22 W/m2K'],
  },
  {
    entityId: ENTITY_IDS.wallWest,
    entityType: 'envelope:wall',
    label: 'West wall',
    material: { name: 'AAC blockwork', grade: '200mm' },
    dimensions: v(0.2, 3.0, 6.0),
    quantity: { value: '18.0', unit: 'm2' },
    phase: 'phase-walls',
    status: 'complete',
    cost: { lineId: 'line:cs-wall-west', currency: 'EUR', amount: '1440.00' },
    constraints: ['U-value 0.22 W/m2K'],
  },
  {
    entityId: ENTITY_IDS.doorFront,
    entityType: 'envelope:door',
    label: 'Front entrance door',
    material: { name: 'Insulated steel door', grade: 'Thermal 1.2 W/m2K' },
    dimensions: v(1.0, 2.0, 0.25),
    quantity: { value: '1', unit: 'nr' },
    phase: 'phase-walls',
    status: 'complete',
    cost: { lineId: 'line:cs-door-front', currency: 'EUR', amount: '780.00' },
    constraints: ['Clear width 1000mm; min 2100mm height'],
  },
  {
    entityId: ENTITY_IDS.windowSouth01,
    entityType: 'envelope:window',
    label: 'South window SW',
    material: { name: 'Aluminium DGU', grade: '1.4 W/m2K' },
    dimensions: v(1.2, 1.2, 0.05),
    quantity: { value: '1.44', unit: 'm2' },
    phase: 'phase-walls',
    status: 'complete',
    cost: { lineId: 'line:cs-window-south-01', currency: 'EUR', amount: '259.20' },
    constraints: ['Sill 1000mm AFFL; safety glazing'],
  },
  {
    entityId: ENTITY_IDS.windowSouth02,
    entityType: 'envelope:window',
    label: 'South window SE',
    material: { name: 'Aluminium DGU', grade: '1.4 W/m2K' },
    dimensions: v(1.2, 1.2, 0.05),
    quantity: { value: '1.44', unit: 'm2' },
    phase: 'phase-walls',
    status: 'complete',
    cost: { lineId: 'line:cs-window-south-02', currency: 'EUR', amount: '259.20' },
    constraints: ['Sill 1000mm AFFL; safety glazing'],
  },
  {
    entityId: ENTITY_IDS.roofCladding,
    entityType: 'envelope:roof',
    label: 'Roof cladding + waterproofing',
    material: { name: 'Single-ply membrane + insulation', grade: '120mm PIR' },
    dimensions: v(8.6, 0.05, 6.6),
    quantity: { value: '56.76', unit: 'm2' },
    phase: 'phase-roof',
    status: 'complete',
    cost: { lineId: 'line:cs-roof-cladding', currency: 'EUR', amount: '4540.80' },
    constraints: ['U-value 0.18 W/m2K; 20-yr warranty'],
  },
  // MEP
  {
    entityId: ENTITY_IDS.electricalPanel,
    entityType: 'mep:panel',
    label: 'Main distribution panel MD-1',
    material: { name: 'Steel enclosure', grade: 'IP54' },
    dimensions: v(0.8, 1.2, 0.2),
    quantity: { value: '1', unit: 'nr' },
    phase: 'phase-mep',
    status: 'complete',
    cost: { lineId: 'line:cs-electrical-panel', currency: 'EUR', amount: '1250.00' },
    constraints: ['100A 3-phase; surge protected'],
  },
  {
    entityId: ENTITY_IDS.lightingCircuit,
    entityType: 'mep:riser',
    label: 'Lighting circuit riser',
    material: { name: 'PVC conduit + CAT6', grade: '32mm' },
    dimensions: v(0.05, 4.0, 0.05),
    quantity: { value: '4.0', unit: 'm' },
    phase: 'phase-mep',
    status: 'complete',
    cost: { lineId: 'line:cs-lighting-circuit', currency: 'EUR', amount: '160.00' },
    constraints: ['Separate from power circuits'],
  },
  {
    entityId: ENTITY_IDS.plumbingRiser,
    entityType: 'mep:riser',
    label: 'Plumbing riser (domestic water)',
    material: { name: 'PEX hot/cold', grade: '25mm' },
    dimensions: v(0.08, 3.0, 0.08),
    quantity: { value: '3.0', unit: 'm' },
    phase: 'phase-mep',
    status: 'in-progress',
    cost: { lineId: 'line:cs-plumbing-riser', currency: 'EUR', amount: '90.00' },
    constraints: ['Insulated; min 20mm flow pressure'],
  },
  {
    entityId: ENTITY_IDS.hvacDuct,
    entityType: 'mep:duct',
    label: 'HVAC supply duct run',
    material: { name: 'Galvanised ductwork', grade: '400x250mm' },
    dimensions: v(4.0, 0.25, 0.25),
    quantity: { value: '4.0', unit: 'm' },
    phase: 'phase-mep',
    status: 'in-progress',
    cost: { lineId: 'line:cs-hvac-duct', currency: 'EUR', amount: '320.00' },
    constraints: ['Clash risk with legacy conduit (W071-finding-002)'],
  },
  {
    entityId: ENTITY_IDS.hvacUnit,
    entityType: 'mep:unit',
    label: 'Roof-top HVAC unit',
    material: { name: 'Split-system RTU', grade: '12kW inverter' },
    dimensions: v(1.5, 0.6, 1.0),
    quantity: { value: '1', unit: 'nr' },
    phase: 'phase-mep',
    status: 'in-progress',
    cost: { lineId: 'line:cs-hvac-unit', currency: 'EUR', amount: '4200.00' },
    constraints: ['Roof load capacity verified'],
  },
  {
    entityId: ENTITY_IDS.drainagePipe,
    entityType: 'mep:pipe',
    label: 'Foul drainage run',
    material: { name: 'uPVC underground', grade: '110mm SDR 41' },
    dimensions: v(0.1, 8.0, 0.1),
    quantity: { value: '8.0', unit: 'm' },
    phase: 'phase-mep',
    status: 'complete',
    cost: { lineId: 'line:cs-drainage-pipe', currency: 'EUR', amount: '240.00' },
    constraints: ['1:80 fall; min 600mm cover'],
  },
  {
    entityId: ENTITY_IDS.legacyConduit,
    entityType: 'mep:conduit',
    label: 'LEGACY conduit L2 (hidden clash risk)',
    material: { name: 'Old steel conduit', grade: '25mm (legacy)' },
    dimensions: v(0.05, 4.0, 0.05),
    quantity: { value: '4.0', unit: 'm' },
    phase: 'phase-mep',
    status: 'blocked',
    cost: { lineId: 'line:cs-legacy-conduit', currency: 'EUR', amount: '0.00' },
    constraints: ['HIDDEN — clash with HVAC duct (W071-finding-002)'],
  },
  // FINISHES
  {
    entityId: ENTITY_IDS.ceiling,
    entityType: 'finishes:ceiling',
    label: 'Suspended ceiling',
    material: { name: 'Mineral tile ceiling', grade: '600x600 acoustic' },
    dimensions: v(8.0, 0.05, 6.0),
    quantity: { value: '48.0', unit: 'm2' },
    phase: 'phase-finishes',
    status: 'pending',
    cost: { lineId: 'line:cs-ceiling', currency: 'EUR', amount: '1920.00' },
    constraints: ['2700mm AFFL; access tiles at MEP'],
  },
  {
    entityId: ENTITY_IDS.floor,
    entityType: 'finishes:floor',
    label: 'Floor finish (screed + vinyl)',
    material: { name: 'Screed + vinyl sheet', grade: '75mm + 2mm' },
    dimensions: v(8.0, 0.05, 6.0),
    quantity: { value: '48.0', unit: 'm2' },
    phase: 'phase-finishes',
    status: 'pending',
    cost: { lineId: 'line:cs-floor-finish', currency: 'EUR', amount: '2160.00' },
    constraints: ['Slip-resistance R10; wheelchair-grade'],
  },
  {
    entityId: ENTITY_IDS.paintWall,
    entityType: 'finishes:paint',
    label: 'Wall paint (interior)',
    material: { name: 'Acrylic emulsion', grade: 'Contract matt' },
    dimensions: v(8.0, 2.4, 0.02),
    quantity: { value: '78.0', unit: 'm2' },
    phase: 'phase-finishes',
    status: 'pending',
    cost: { lineId: 'line:cs-paint-wall', currency: 'EUR', amount: '624.00' },
    constraints: ['Two coats; VOC < 10g/L'],
  },
  {
    entityId: ENTITY_IDS.fixtures,
    entityType: 'finishes:fixture',
    label: 'Sanitary + lighting fixtures',
    material: { name: 'WC + basin + LED fittings', grade: 'Water-efficient' },
    dimensions: v(2.0, 0.15, 0.5),
    quantity: { value: '1', unit: 'set' },
    phase: 'phase-finishes',
    status: 'pending',
    cost: { lineId: 'line:cs-fixtures', currency: 'EUR', amount: '1850.00' },
    constraints: ['Water label; LED 4000K 300 lumens/m'],
  },
];

/** The total entity count of the construction-solution fixture. */
export const ENTITY_COUNT = ENTITY_GEOMETRY.length;
