/**
 * COMPILE-TIME CONTRACT SYNC (the type-level half of the W008 contract
 * guarantee; the JSON-Schema half is test/contract-drift.test.ts).
 *
 * Every exported alias below compiles ONLY while the zod validators in
 * src/schema.ts infer exactly the published contract types in
 * src/types.ts.
 */
import type { z } from 'zod';
import type { Equals, Expect } from './type-utils';
import type { HostFunctionDeclaration, TrustClassGrantCeiling, WasmValueType } from './version';
import type {
  CapabilityBinding,
  CapabilityInvokeRequest,
  CapabilityInvokeResponse,
  ClockReadRequest,
  ClockReadResponse,
  ComponentFunctionDeclaration,
  ComponentInterfaceDeclaration,
  DeclarativeEntryPoint,
  EntryPointDeclaration,
  EntryPointName,
  ExtensionDataHandling,
  ExtensionGrant,
  ExtensionId,
  ExtensionManifest,
  ExtensionRegistration,
  ExtensionSideEffect,
  ExtensionVersion,
  LayoutSection,
  LogWriteRequest,
  LogWriteResponse,
  RemoteEntryPoint,
  RemoteOperationDeclaration,
  RemoteServiceDescriptor,
  ResourceScope,
  StorageReadRequest,
  StorageReadResponse,
  StorageWriteRequest,
  StorageWriteResponse,
  UiEntryPoint,
  WasmComponentDescriptor,
  WasmEntryPoint,
  WasmParamDeclaration,
  WorldReadRequest,
  WorldReadResponse,
  EvidenceAppendRequest,
  EvidenceAppendResponse,
  ExtensionSdkIssue,
} from './types';
import type {
  CapabilityBindingSchema,
  CapabilityInvokeRequestSchema,
  CapabilityInvokeResponseSchema,
  ClockReadRequestSchema,
  ClockReadResponseSchema,
  ComponentFunctionDeclarationSchema,
  ComponentInterfaceDeclarationSchema,
  DataHandlingClassificationSchema,
  DeclarativeEntryPointSchema,
  EntryPointDeclarationSchema,
  EntryPointNameSchema,
  ExtensionDataHandlingSchema,
  ExtensionFlavorSchema,
  ExtensionGrantSchema,
  ExtensionIdSchema,
  ExtensionManifestSchema,
  ExtensionManifestVersionSchema,
  ExtensionRegistrationSchema,
  ExtensionSideEffectSchema,
  ExtensionTrustClassSchema,
  HostFunctionDeclarationSchema,
  HostFunctionIdSchema,
  HostLogLevelSchema,
  LayoutSectionSchema,
  LogWriteRequestSchema,
  LogWriteResponseSchema,
  RemoteEntryPointSchema,
  RemoteOperationDeclarationSchema,
  RemoteServiceDescriptorSchema,
  RemoteTransportKindSchema,
  ResourceAccessSchema,
  ResourceDomainSchema,
  ResourceScopeSchema,
  SideEffectKindSchema,
  StorageReadRequestSchema,
  StorageReadResponseSchema,
  StorageWriteRequestSchema,
  StorageWriteResponseSchema,
  TrustClassGrantCeilingSchema,
  UiEntryPointSchema,
  UiSurfaceKindSchema,
  WasmComponentDescriptorSchema,
  WasmComponentDescriptorVersionSchema,
  WasmEntryPointSchema,
  WasmParamDeclarationSchema,
  WasmSectionKindSchema,
  WasmValueTypeSchema,
  WorldReadRequestSchema,
  WorldReadResponseSchema,
  EvidenceAppendRequestSchema,
  EvidenceAppendResponseSchema,
} from './schema';

export type ExtensionSdkSchemaSync = [
  Expect<Equals<z.infer<typeof ExtensionManifestVersionSchema>, 1>>,
  Expect<Equals<z.infer<typeof ExtensionIdSchema>, ExtensionId>>,
  Expect<Equals<z.infer<typeof EntryPointNameSchema>, EntryPointName>>,
  Expect<Equals<z.infer<typeof ExtensionFlavorSchema>, 'declarative' | 'ui' | 'wasm' | 'remote'>>,
  Expect<Equals<z.infer<typeof ExtensionTrustClassSchema>, 't0' | 't1' | 't2' | 't3' | 't4'>>,
  Expect<Equals<z.infer<typeof ResourceDomainSchema>, 'world' | 'evidence' | 'storage' | 'capability'>>,
  Expect<Equals<z.infer<typeof ResourceAccessSchema>, 'read' | 'append' | 'write' | 'invoke'>>,
  Expect<Equals<z.infer<typeof ResourceScopeSchema>, ResourceScope>>,
  Expect<Equals<z.infer<typeof HostFunctionIdSchema>, 'capability.invoke' | 'clock.read' | 'evidence.append' | 'log.write' | 'storage.read' | 'storage.write' | 'world.read'>>,
  Expect<Equals<z.infer<typeof HostLogLevelSchema>, 'debug' | 'error' | 'info' | 'warn'>>,
  Expect<Equals<z.infer<typeof HostFunctionDeclarationSchema>, HostFunctionDeclaration>>,
  Expect<Equals<z.infer<typeof TrustClassGrantCeilingSchema>, TrustClassGrantCeiling>>,
  Expect<Equals<z.infer<typeof CapabilityBindingSchema>, CapabilityBinding>>,
  Expect<Equals<z.infer<typeof ExtensionGrantSchema>, ExtensionGrant>>,
  Expect<Equals<z.infer<typeof ExtensionSideEffectSchema>, ExtensionSideEffect>>,
  Expect<Equals<z.infer<typeof DataHandlingClassificationSchema>, 'sandbox-only' | 'tenant-scoped' | 'external-transfer'>>,
  Expect<Equals<z.infer<typeof ExtensionDataHandlingSchema>, ExtensionDataHandling>>,
  Expect<Equals<z.infer<typeof SideEffectKindSchema>, 'action-proposal' | 'evidence-append' | 'external-effect' | 'sandbox-state-write'>>,
  Expect<Equals<z.infer<typeof WasmParamDeclarationSchema>, WasmParamDeclaration>>,
  Expect<Equals<z.infer<typeof WasmValueTypeSchema>, WasmValueType>>,
  Expect<Equals<z.infer<typeof WasmSectionKindSchema>, 'adapter' | 'core-module' | 'custom'>>,
  Expect<Equals<z.infer<typeof ComponentFunctionDeclarationSchema>, ComponentFunctionDeclaration>>,
  Expect<Equals<z.infer<typeof ComponentInterfaceDeclarationSchema>, ComponentInterfaceDeclaration>>,
  Expect<Equals<z.infer<typeof LayoutSectionSchema>, LayoutSection>>,
  Expect<Equals<z.infer<typeof WasmComponentDescriptorSchema>, WasmComponentDescriptor>>,
  Expect<Equals<z.infer<typeof WasmComponentDescriptorVersionSchema>, 1>>,
  Expect<Equals<z.infer<typeof RemoteTransportKindSchema>, 'custom' | 'grpc' | 'http' | 'mcp'>>,
  Expect<Equals<z.infer<typeof RemoteOperationDeclarationSchema>, RemoteOperationDeclaration>>,
  Expect<Equals<z.infer<typeof RemoteServiceDescriptorSchema>, RemoteServiceDescriptor>>,
  Expect<Equals<z.infer<typeof DeclarativeEntryPointSchema>, DeclarativeEntryPoint>>,
  Expect<Equals<z.infer<typeof UiEntryPointSchema>, UiEntryPoint>>,
  Expect<Equals<z.infer<typeof WasmEntryPointSchema>, WasmEntryPoint>>,
  Expect<Equals<z.infer<typeof RemoteEntryPointSchema>, RemoteEntryPoint>>,
  Expect<Equals<z.infer<typeof EntryPointDeclarationSchema>, EntryPointDeclaration>>,
  Expect<Equals<z.infer<typeof ExtensionManifestSchema>, ExtensionManifest>>,
  Expect<Equals<z.infer<typeof ExtensionRegistrationSchema>, ExtensionRegistration>>,
  // Host-function payload contracts.
  Expect<Equals<z.infer<typeof ClockReadRequestSchema>, ClockReadRequest>>,
  Expect<Equals<z.infer<typeof ClockReadResponseSchema>, ClockReadResponse>>,
  Expect<Equals<z.infer<typeof LogWriteRequestSchema>, LogWriteRequest>>,
  Expect<Equals<z.infer<typeof LogWriteResponseSchema>, LogWriteResponse>>,
  Expect<Equals<z.infer<typeof WorldReadRequestSchema>, WorldReadRequest>>,
  Expect<Equals<z.infer<typeof WorldReadResponseSchema>, WorldReadResponse>>,
  Expect<Equals<z.infer<typeof EvidenceAppendRequestSchema>, EvidenceAppendRequest>>,
  Expect<Equals<z.infer<typeof EvidenceAppendResponseSchema>, EvidenceAppendResponse>>,
  Expect<Equals<z.infer<typeof CapabilityInvokeRequestSchema>, CapabilityInvokeRequest>>,
  Expect<Equals<z.infer<typeof CapabilityInvokeResponseSchema>, CapabilityInvokeResponse>>,
  Expect<Equals<z.infer<typeof StorageReadRequestSchema>, StorageReadRequest>>,
  Expect<Equals<z.infer<typeof StorageReadResponseSchema>, StorageReadResponse>>,
  Expect<Equals<z.infer<typeof StorageWriteRequestSchema>, StorageWriteRequest>>,
  Expect<Equals<z.infer<typeof StorageWriteResponseSchema>, StorageWriteResponse>>,
  Expect<Equals<z.infer<typeof UiSurfaceKindSchema>, 'inspector' | 'overlay' | 'panel'>>,
];

/** Result/error surface shape sanity. */
export type ExtensionSdkResultSync = [
  Expect<Equals<ExtensionRegistration['digest'], import('@epoch/agent-protocol').Sha256Hex>>,
  Expect<Equals<ExtensionSdkIssue, { readonly path: string; readonly message: string }>>,
  Expect<Equals<ExtensionManifest['schemaVersion'], 1>>,
  Expect<Equals<ExtensionManifest['version'], ExtensionVersion>>,
];
