/**
 * The extension-sdk schema surface registry: every data type published
 * at the `@epoch/extension-sdk` ownership boundary, paired with its zod
 * schema (W008 publishes its versioned contract surface inside the
 * package, following the W007 in-package pattern; see
 * src/contract-emission.ts and test/contract-drift.test.ts).
 */
import type { ZodType } from 'zod';
import { SemverCoreSchema } from '@epoch/capability-registry';
import {
  CapabilityBindingSchema,
  CapabilityInvokeRequestSchema,
  CapabilityInvokeResponseSchema,
  ClockReadRequestSchema,
  ClockReadResponseSchema,
  ComponentFunctionDeclarationSchema,
  ComponentInterfaceDeclarationSchema,
  ContributionKindSchema,
  DataHandlingClassificationSchema,
  DeclarativeEntryPointSchema,
  EntryPointDeclarationSchema,
  EntryPointNameSchema,
  EvidenceAppendRequestSchema,
  EvidenceAppendResponseSchema,
  ExtensionDataHandlingSchema,
  ExtensionFlavorSchema,
  ExtensionGrantSchema,
  ExtensionIdSchema,
  ExtensionManifestSchema,
  ExtensionManifestVersionSchema,
  ExtensionRegistrationSchema,
  ExtensionSideEffectSchema,
  ExtensionTrustClassSchema,
  HostFunctionDeclarationSchema,
  HostFunctionIdSchema,
  HostLogLevelSchema,
  LayoutSectionSchema,
  LogWriteRequestSchema,
  LogWriteResponseSchema,
  RemoteEntryPointSchema,
  RemoteOperationDeclarationSchema,
  RemoteServiceDescriptorSchema,
  RemoteTransportKindSchema,
  ResourceAccessSchema,
  ResourceDomainSchema,
  ResourceScopeSchema,
  SideEffectKindSchema,
  StorageReadRequestSchema,
  StorageReadResponseSchema,
  StorageWriteRequestSchema,
  StorageWriteResponseSchema,
  TrustClassGrantCeilingSchema,
  UiEntryPointSchema,
  UiSurfaceKindSchema,
  WasmComponentDescriptorSchema,
  WasmComponentDescriptorVersionSchema,
  WasmParamDeclarationSchema,
  WasmSectionKindSchema,
  WasmValueTypeSchema,
  WorldReadRequestSchema,
  WorldReadResponseSchema,
} from './schema';

/** One entry of the published data-type surface. */
export interface SchemaSurfaceEntry {
  readonly type: string;
  readonly schema: ZodType;
}

/** The complete, ordered data-type surface of the extension-sdk contract v1. */
export const EXTENSION_SDK_SCHEMA_SURFACE: readonly SchemaSurfaceEntry[] = [
  { type: 'CapabilityBinding', schema: CapabilityBindingSchema },
  { type: 'CapabilityInvokeRequest', schema: CapabilityInvokeRequestSchema },
  { type: 'CapabilityInvokeResponse', schema: CapabilityInvokeResponseSchema },
  { type: 'ClockReadRequest', schema: ClockReadRequestSchema },
  { type: 'ClockReadResponse', schema: ClockReadResponseSchema },
  { type: 'ComponentFunctionDeclaration', schema: ComponentFunctionDeclarationSchema },
  { type: 'ComponentInterfaceDeclaration', schema: ComponentInterfaceDeclarationSchema },
  { type: 'ContributionKind', schema: ContributionKindSchema },
  { type: 'DataHandlingClassification', schema: DataHandlingClassificationSchema },
  { type: 'DeclarativeEntryPoint', schema: DeclarativeEntryPointSchema },
  { type: 'EntryPointDeclaration', schema: EntryPointDeclarationSchema },
  { type: 'EntryPointName', schema: EntryPointNameSchema },
  { type: 'EvidenceAppendRequest', schema: EvidenceAppendRequestSchema },
  { type: 'EvidenceAppendResponse', schema: EvidenceAppendResponseSchema },
  { type: 'ExtensionDataHandling', schema: ExtensionDataHandlingSchema },
  { type: 'ExtensionFlavor', schema: ExtensionFlavorSchema },
  { type: 'ExtensionGrant', schema: ExtensionGrantSchema },
  { type: 'ExtensionId', schema: ExtensionIdSchema },
  { type: 'ExtensionManifest', schema: ExtensionManifestSchema },
  { type: 'ExtensionManifestVersion', schema: ExtensionManifestVersionSchema },
  { type: 'ExtensionRegistration', schema: ExtensionRegistrationSchema },
  { type: 'ExtensionSideEffect', schema: ExtensionSideEffectSchema },
  { type: 'ExtensionTrustClass', schema: ExtensionTrustClassSchema },
  { type: 'HostFunctionDeclaration', schema: HostFunctionDeclarationSchema },
  { type: 'HostFunctionId', schema: HostFunctionIdSchema },
  { type: 'HostLogLevel', schema: HostLogLevelSchema },
  { type: 'LayoutSection', schema: LayoutSectionSchema },
  { type: 'LogWriteRequest', schema: LogWriteRequestSchema },
  { type: 'LogWriteResponse', schema: LogWriteResponseSchema },
  { type: 'RemoteEntryPoint', schema: RemoteEntryPointSchema },
  { type: 'RemoteOperationDeclaration', schema: RemoteOperationDeclarationSchema },
  { type: 'RemoteServiceDescriptor', schema: RemoteServiceDescriptorSchema },
  { type: 'RemoteTransportKind', schema: RemoteTransportKindSchema },
  { type: 'ResourceAccess', schema: ResourceAccessSchema },
  { type: 'ResourceDomain', schema: ResourceDomainSchema },
  { type: 'ResourceScope', schema: ResourceScopeSchema },
  { type: 'SemverCore', schema: SemverCoreSchema },
  { type: 'SideEffectKind', schema: SideEffectKindSchema },
  { type: 'StorageReadRequest', schema: StorageReadRequestSchema },
  { type: 'StorageReadResponse', schema: StorageReadResponseSchema },
  { type: 'StorageWriteRequest', schema: StorageWriteRequestSchema },
  { type: 'StorageWriteResponse', schema: StorageWriteResponseSchema },
  { type: 'TrustClassGrantCeiling', schema: TrustClassGrantCeilingSchema },
  { type: 'UiEntryPoint', schema: UiEntryPointSchema },
  { type: 'UiSurfaceKind', schema: UiSurfaceKindSchema },
  { type: 'WasmComponentDescriptor', schema: WasmComponentDescriptorSchema },
  { type: 'WasmComponentDescriptorVersion', schema: WasmComponentDescriptorVersionSchema },
  { type: 'WasmParamDeclaration', schema: WasmParamDeclarationSchema },
  { type: 'WasmSectionKind', schema: WasmSectionKindSchema },
  { type: 'WasmValueType', schema: WasmValueTypeSchema },
  { type: 'WorldReadRequest', schema: WorldReadRequestSchema },
  { type: 'WorldReadResponse', schema: WorldReadResponseSchema },
];
