/**
 * COMPILE-TIME CONTRACT SYNC (the type-level half of the W045 contract
 * guarantee; the JSON-Schema half is test/contract-drift.test.ts).
 *
 * Every exported alias below compiles ONLY while the zod validators in
 * src/schema.ts infer exactly the published contract types in src/types.ts.
 */
import type { z } from 'zod';
import type { Equals, Expect } from './type-utils';
import type {
  CandidateAssignment,
  CandidateEvaluationEvidence,
  CandidateEvaluationState,
  CandidateId,
  CandidateKind,
  CandidateMatch,
  CandidateProfile,
  CandidateProvenance,
  CandidateSecurity,
  CapabilityDemand,
  CapabilityDemandId,
  CapabilityDemandSet,
  CapabilityDemandTemplate,
  CapabilityGap,
  CapabilityGapId,
  CapabilityGapState,
  ClaimBasis,
  ClaimedCapability,
  ConstraintSignal,
  CostClaim,
  CriterionResult,
  DiscoveryCadenceKind,
  DiscoveryError,
  DiscoveryInput,
  DiscoveryIssue,
  DiscoveryRun,
  DiscoveryRunArtifact,
  DiscoveryRunId,
  DiscoveryRunKind,
  DiscoveryRunTrigger,
  DiscoverySchedule,
  DiscoveryStageLink,
  DiscoveryStageName,
  DiscoveryTenantId,
  DiscoveryTrigger,
  Sha256Hex,
  Timestamp,
  DomainPackContribution,
  DomainPackProposalDetail,
  DueDiscoveryRun,
  EcosystemDiscoveryRequest,
  EcosystemProposal,
  EcosystemProposalEvidence,
  EcosystemProposalId,
  EcosystemProposalKind,
  EcosystemProposalStatus,
  EcosystemScanReport,
  EvaluationCriterion,
  EvaluationCriterionKind,
  EvaluationMetric,
  EvidenceSignal,
  GapTransition,
  HandoffEdge,
  HumanDeclaration,
  LatencyClaim,
  MoneyAmount,
  OperationRef,
  OrganizationEstimates,
  OrganizationEvaluation,
  OrganizationId,
  OrganizationProposal,
  OrganizationRoleBinding,
  OrganizationSelection,
  OutputContractEntry,
  PolicyApproval,
  PromotionId,
  PromotionRecord,
  QualityTarget,
  RepresentationKind,
  RoleAuthorityBoundary,
  RoleInterfaceEntry,
  RolePlanningBehavior,
  RoleProposal,
  RoleProposalId,
  RoleProvenance,
  RoleResolution,
  RoleTemplate,
  SandboxReport,
  SourceArtifact,
  SourceScanQuery,
  SourceScanResult,
  SupervisionEdge,
  TaskDescription,
  TaskSignal,
  TaskSignalBinding,
  TaskSignalKind,
  TemplateApplicability,
  UniversalLifecycleStage,
  WorldRef,
} from './types';
import type {
  CandidateAssignmentSchema,
  CandidateEvaluationEvidenceSchema,
  CandidateEvaluationStateSchema,
  CandidateIdSchema,
  CandidateKindSchema,
  CandidateMatchSchema,
  CandidateProfileSchema,
  CandidateProvenanceSchema,
  CandidateSecuritySchema,
  CapabilityDemandIdSchema,
  CapabilityDemandSchema,
  CapabilityDemandSetSchema,
  CapabilityDemandTemplateSchema,
  CapabilityGapIdSchema,
  CapabilityGapSchema,
  CapabilityGapStateSchema,
  ClaimBasisSchema,
  ClaimedCapabilitySchema,
  ConstraintSignalSchema,
  CostClaimSchema,
  CriterionResultSchema,
  DiscoveryCadenceKindSchema,
  DiscoveryErrorSchema,
  DiscoveryInputSchema,
  DiscoveryIssueSchema,
  DiscoveryRunArtifactSchema,
  DiscoveryRunIdSchema,
  DiscoveryRunKindSchema,
  DiscoveryRunSchema,
  DiscoveryRunTriggerSchema,
  DiscoveryScheduleSchema,
  DiscoverySha256HexSchema,
  DiscoveryStageLinkSchema,
  DiscoveryStageNameSchema,
  DiscoveryTenantIdSchema,
  DiscoveryTimestampSchema,
  DiscoveryTriggerSchema,
  DomainPackContributionSchema,
  DomainPackProposalDetailSchema,
  DueDiscoveryRunSchema,
  EcosystemDiscoveryRequestSchema,
  EcosystemProposalEvidenceSchema,
  EcosystemProposalIdSchema,
  EcosystemProposalKindSchema,
  EcosystemProposalSchema,
  EcosystemProposalStatusSchema,
  EcosystemScanReportSchema,
  EvaluationCriterionKindSchema,
  EvaluationCriterionSchema,
  EvaluationMetricSchema,
  EvidenceSignalSchema,
  GapTransitionSchema,
  HandoffEdgeSchema,
  HumanDeclarationSchema,
  LatencyClaimSchema,
  MoneyAmountSchema,
  OperationRefSchema,
  OrganizationEstimatesSchema,
  OrganizationEvaluationSchema,
  OrganizationIdSchema,
  OrganizationProposalSchema,
  OrganizationRoleBindingSchema,
  OrganizationSelectionSchema,
  OutputContractEntrySchema,
  PolicyApprovalSchema,
  PromotionIdSchema,
  PromotionRecordSchema,
  QualityTargetSchema,
  RepresentationKindSchema,
  RoleAuthorityBoundarySchema,
  RoleInterfaceEntrySchema,
  RolePlanningBehaviorSchema,
  RoleProposalIdSchema,
  RoleProposalSchema,
  RoleProvenanceSchema,
  RoleResolutionSchema,
  RoleTemplateSchema,
  SandboxReportSchema,
  SourceArtifactSchema,
  SourceScanQuerySchema,
  SourceScanResultSchema,
  SupervisionEdgeSchema,
  TaskDescriptionSchema,
  TaskSignalBindingSchema,
  TaskSignalKindSchema,
  TaskSignalSchema,
  TemplateApplicabilitySchema,
  UniversalLifecycleStageSchema,
  WorldRefSchema,
} from './schema';

/** Every published type must be zod-inferred identically. */
export type CapabilityDiscoverySchemaSync = [
  Expect<Equals<z.infer<typeof DiscoveryTimestampSchema>, Timestamp>>,
  Expect<Equals<z.infer<typeof DiscoverySha256HexSchema>, Sha256Hex>>,
  Expect<Equals<z.infer<typeof DiscoveryTenantIdSchema>, DiscoveryTenantId>>,
  Expect<Equals<z.infer<typeof DiscoveryRunIdSchema>, DiscoveryRunId>>,
  Expect<Equals<z.infer<typeof CapabilityDemandIdSchema>, CapabilityDemandId>>,
  Expect<Equals<z.infer<typeof RoleProposalIdSchema>, RoleProposalId>>,
  Expect<Equals<z.infer<typeof CandidateIdSchema>, CandidateId>>,
  Expect<Equals<z.infer<typeof CapabilityGapIdSchema>, CapabilityGapId>>,
  Expect<Equals<z.infer<typeof OrganizationIdSchema>, OrganizationId>>,
  Expect<Equals<z.infer<typeof EcosystemProposalIdSchema>, EcosystemProposalId>>,
  Expect<Equals<z.infer<typeof PromotionIdSchema>, PromotionId>>,
  Expect<Equals<z.infer<typeof UniversalLifecycleStageSchema>, UniversalLifecycleStage>>,
  Expect<Equals<z.infer<typeof TaskSignalKindSchema>, TaskSignalKind>>,
  Expect<Equals<z.infer<typeof RepresentationKindSchema>, RepresentationKind>>,
  Expect<Equals<z.infer<typeof CapabilityGapStateSchema>, CapabilityGapState>>,
  Expect<Equals<z.infer<typeof CandidateKindSchema>, CandidateKind>>,
  Expect<Equals<z.infer<typeof CandidateEvaluationStateSchema>, CandidateEvaluationState>>,
  Expect<Equals<z.infer<typeof ClaimBasisSchema>, ClaimBasis>>,
  Expect<Equals<z.infer<typeof EvaluationCriterionKindSchema>, EvaluationCriterionKind>>,
  Expect<Equals<z.infer<typeof EvaluationMetricSchema>, EvaluationMetric>>,
  Expect<Equals<z.infer<typeof DiscoveryRunKindSchema>, DiscoveryRunKind>>,
  Expect<Equals<z.infer<typeof DiscoveryTriggerSchema>, DiscoveryTrigger>>,
  Expect<Equals<z.infer<typeof DiscoveryStageNameSchema>, DiscoveryStageName>>,
  Expect<Equals<z.infer<typeof EcosystemProposalKindSchema>, EcosystemProposalKind>>,
  Expect<Equals<z.infer<typeof EcosystemProposalStatusSchema>, EcosystemProposalStatus>>,
  Expect<Equals<z.infer<typeof DiscoveryCadenceKindSchema>, DiscoveryCadenceKind>>,
  Expect<Equals<z.infer<typeof OperationRefSchema>, OperationRef>>,
  Expect<Equals<z.infer<typeof QualityTargetSchema>, QualityTarget>>,
  Expect<Equals<z.infer<typeof MoneyAmountSchema>, MoneyAmount>>,
  Expect<Equals<z.infer<typeof WorldRefSchema>, WorldRef>>,
  Expect<Equals<z.infer<typeof EvidenceSignalSchema>, EvidenceSignal>>,
  Expect<Equals<z.infer<typeof ConstraintSignalSchema>, ConstraintSignal>>,
  Expect<Equals<z.infer<typeof TaskSignalSchema>, TaskSignal>>,
  Expect<Equals<z.infer<typeof TaskDescriptionSchema>, TaskDescription>>,
  Expect<Equals<z.infer<typeof TemplateApplicabilitySchema>, TemplateApplicability>>,
  Expect<Equals<z.infer<typeof CapabilityDemandTemplateSchema>, CapabilityDemandTemplate>>,
  Expect<Equals<z.infer<typeof RoleTemplateSchema>, RoleTemplate>>,
  Expect<Equals<z.infer<typeof TaskSignalBindingSchema>, TaskSignalBinding>>,
  Expect<Equals<z.infer<typeof DomainPackContributionSchema>, DomainPackContribution>>,
  Expect<Equals<z.infer<typeof DiscoveryInputSchema>, DiscoveryInput>>,
  Expect<Equals<z.infer<typeof OutputContractEntrySchema>, OutputContractEntry>>,
  Expect<Equals<z.infer<typeof DiscoveryIssueSchema>, DiscoveryIssue>>,
  Expect<Equals<z.infer<typeof CapabilityDemandSchema>, CapabilityDemand>>,
  Expect<Equals<z.infer<typeof CapabilityDemandSetSchema>, CapabilityDemandSet>>,
  Expect<Equals<z.infer<typeof RoleInterfaceEntrySchema>, RoleInterfaceEntry>>,
  Expect<Equals<z.infer<typeof RolePlanningBehaviorSchema>, RolePlanningBehavior>>,
  Expect<Equals<z.infer<typeof RoleAuthorityBoundarySchema>, RoleAuthorityBoundary>>,
  Expect<Equals<z.infer<typeof RoleProvenanceSchema>, RoleProvenance>>,
  Expect<Equals<z.infer<typeof RoleProposalSchema>, RoleProposal>>,
  Expect<Equals<z.infer<typeof ClaimedCapabilitySchema>, ClaimedCapability>>,
  Expect<Equals<z.infer<typeof LatencyClaimSchema>, LatencyClaim>>,
  Expect<Equals<z.infer<typeof CostClaimSchema>, CostClaim>>,
  Expect<Equals<z.infer<typeof CandidateProvenanceSchema>, CandidateProvenance>>,
  Expect<Equals<z.infer<typeof CandidateSecuritySchema>, CandidateSecurity>>,
  Expect<Equals<z.infer<typeof CandidateProfileSchema>, CandidateProfile>>,
  Expect<Equals<z.infer<typeof HumanDeclarationSchema>, HumanDeclaration>>,
  Expect<Equals<z.infer<typeof CandidateMatchSchema>, CandidateMatch>>,
  Expect<Equals<z.infer<typeof CandidateAssignmentSchema>, CandidateAssignment>>,
  Expect<Equals<z.infer<typeof RoleResolutionSchema>, RoleResolution>>,
  Expect<Equals<z.infer<typeof GapTransitionSchema>, GapTransition>>,
  Expect<Equals<z.infer<typeof CapabilityGapSchema>, CapabilityGap>>,
  Expect<Equals<z.infer<typeof EcosystemDiscoveryRequestSchema>, EcosystemDiscoveryRequest>>,
  Expect<Equals<z.infer<typeof OrganizationRoleBindingSchema>, OrganizationRoleBinding>>,
  Expect<Equals<z.infer<typeof HandoffEdgeSchema>, HandoffEdge>>,
  Expect<Equals<z.infer<typeof SupervisionEdgeSchema>, SupervisionEdge>>,
  Expect<Equals<z.infer<typeof OrganizationEstimatesSchema>, OrganizationEstimates>>,
  Expect<Equals<z.infer<typeof OrganizationProposalSchema>, OrganizationProposal>>,
  Expect<Equals<z.infer<typeof EvaluationCriterionSchema>, EvaluationCriterion>>,
  Expect<Equals<z.infer<typeof CriterionResultSchema>, CriterionResult>>,
  Expect<Equals<z.infer<typeof OrganizationEvaluationSchema>, OrganizationEvaluation>>,
  Expect<Equals<z.infer<typeof OrganizationSelectionSchema>, OrganizationSelection>>,
  Expect<Equals<z.infer<typeof DiscoveryStageLinkSchema>, DiscoveryStageLink>>,
  Expect<Equals<z.infer<typeof DiscoveryRunTriggerSchema>, DiscoveryRunTrigger>>,
  Expect<Equals<z.infer<typeof DiscoveryRunSchema>, DiscoveryRun>>,
  Expect<Equals<z.infer<typeof DiscoveryRunArtifactSchema>, DiscoveryRunArtifact>>,
  Expect<Equals<z.infer<typeof SourceArtifactSchema>, SourceArtifact>>,
  Expect<Equals<z.infer<typeof SourceScanQuerySchema>, SourceScanQuery>>,
  Expect<Equals<z.infer<typeof SourceScanResultSchema>, SourceScanResult>>,
  Expect<Equals<z.infer<typeof SandboxReportSchema>, SandboxReport>>,
  Expect<Equals<z.infer<typeof CandidateEvaluationEvidenceSchema>, CandidateEvaluationEvidence>>,
  Expect<Equals<z.infer<typeof PolicyApprovalSchema>, PolicyApproval>>,
  Expect<Equals<z.infer<typeof PromotionRecordSchema>, PromotionRecord>>,
  Expect<Equals<z.infer<typeof EcosystemScanReportSchema>, EcosystemScanReport>>,
  Expect<Equals<z.infer<typeof EcosystemProposalEvidenceSchema>, EcosystemProposalEvidence>>,
  Expect<Equals<z.infer<typeof DomainPackProposalDetailSchema>, DomainPackProposalDetail>>,
  Expect<Equals<z.infer<typeof EcosystemProposalSchema>, EcosystemProposal>>,
  Expect<Equals<z.infer<typeof DiscoveryScheduleSchema>, DiscoverySchedule>>,
  Expect<Equals<z.infer<typeof DueDiscoveryRunSchema>, DueDiscoveryRun>>,
  Expect<Equals<z.infer<typeof DiscoveryErrorSchema>, DiscoveryError>>,
];
