/**
 * The published schema surface: the ordered list of (type, schema) pairs
 * emitted as JSON Schema under `contracts/capability-discovery/schemas/`.
 */
import type { ZodType } from 'zod';
import * as schemas from './schema';

/** One entry of the published schema surface. */
export interface SchemaSurfaceEntry {
  readonly type: string;
  readonly schema: ZodType;
}

/** The capability-discovery contract surface (ordered, complete). */
export const CAPABILITY_DISCOVERY_SCHEMA_SURFACE: readonly SchemaSurfaceEntry[] = [
  { type: 'CapabilityDiscoveryContractVersion', schema: schemas.DiscoveryContractVersionSchema },
  { type: 'CapabilityDiscoveryRecordVersion', schema: schemas.DiscoveryRecordVersionSchema },
  { type: 'DiscoveryCompilerVersion', schema: schemas.DiscoveryCompilerVersionSchema },
  { type: 'DiscoveryTimestamp', schema: schemas.DiscoveryTimestampSchema },
  { type: 'DiscoverySha256Hex', schema: schemas.DiscoverySha256HexSchema },
  { type: 'DiscoveryTenantId', schema: schemas.DiscoveryTenantIdSchema },
  { type: 'DiscoveryRunId', schema: schemas.DiscoveryRunIdSchema },
  { type: 'CapabilityDemandId', schema: schemas.CapabilityDemandIdSchema },
  { type: 'RoleProposalId', schema: schemas.RoleProposalIdSchema },
  { type: 'CandidateId', schema: schemas.CandidateIdSchema },
  { type: 'CapabilityGapId', schema: schemas.CapabilityGapIdSchema },
  { type: 'OrganizationId', schema: schemas.OrganizationIdSchema },
  { type: 'EcosystemProposalId', schema: schemas.EcosystemProposalIdSchema },
  { type: 'PromotionId', schema: schemas.PromotionIdSchema },
  { type: 'UniversalLifecycleStage', schema: schemas.UniversalLifecycleStageSchema },
  { type: 'TaskSignalKind', schema: schemas.TaskSignalKindSchema },
  { type: 'RepresentationKind', schema: schemas.RepresentationKindSchema },
  { type: 'CapabilityGapState', schema: schemas.CapabilityGapStateSchema },
  { type: 'CandidateKind', schema: schemas.CandidateKindSchema },
  { type: 'CandidateEvaluationState', schema: schemas.CandidateEvaluationStateSchema },
  { type: 'ClaimBasis', schema: schemas.ClaimBasisSchema },
  { type: 'EvaluationCriterionKind', schema: schemas.EvaluationCriterionKindSchema },
  { type: 'EvaluationMetric', schema: schemas.EvaluationMetricSchema },
  { type: 'DiscoveryRunKind', schema: schemas.DiscoveryRunKindSchema },
  { type: 'DiscoveryTrigger', schema: schemas.DiscoveryTriggerSchema },
  { type: 'DiscoveryStageName', schema: schemas.DiscoveryStageNameSchema },
  { type: 'EcosystemProposalKind', schema: schemas.EcosystemProposalKindSchema },
  { type: 'EcosystemProposalStatus', schema: schemas.EcosystemProposalStatusSchema },
  { type: 'DiscoverySourceKind', schema: schemas.DiscoverySourceKindSchema },
  { type: 'DiscoveryCadenceKind', schema: schemas.DiscoveryCadenceKindSchema },
  { type: 'OperationRef', schema: schemas.OperationRefSchema },
  { type: 'QualityTarget', schema: schemas.QualityTargetSchema },
  { type: 'MoneyAmount', schema: schemas.MoneyAmountSchema },
  { type: 'WorldRef', schema: schemas.WorldRefSchema },
  { type: 'EvidenceSignal', schema: schemas.EvidenceSignalSchema },
  { type: 'ConstraintSignal', schema: schemas.ConstraintSignalSchema },
  { type: 'TaskSignal', schema: schemas.TaskSignalSchema },
  { type: 'TaskDescription', schema: schemas.TaskDescriptionSchema },
  { type: 'TemplateApplicability', schema: schemas.TemplateApplicabilitySchema },
  { type: 'CapabilityDemandTemplate', schema: schemas.CapabilityDemandTemplateSchema },
  { type: 'RoleTemplate', schema: schemas.RoleTemplateSchema },
  { type: 'TaskSignalBinding', schema: schemas.TaskSignalBindingSchema },
  { type: 'DomainPackContribution', schema: schemas.DomainPackContributionSchema },
  { type: 'DiscoveryInput', schema: schemas.DiscoveryInputSchema },
  { type: 'OutputContractEntry', schema: schemas.OutputContractEntrySchema },
  { type: 'CapabilityDemand', schema: schemas.CapabilityDemandSchema },
  { type: 'CapabilityDemandSet', schema: schemas.CapabilityDemandSetSchema },
  { type: 'RoleInterfaceEntry', schema: schemas.RoleInterfaceEntrySchema },
  { type: 'RolePlanningBehavior', schema: schemas.RolePlanningBehaviorSchema },
  { type: 'RoleAuthorityBoundary', schema: schemas.RoleAuthorityBoundarySchema },
  { type: 'RoleProvenance', schema: schemas.RoleProvenanceSchema },
  { type: 'RoleProposal', schema: schemas.RoleProposalSchema },
  { type: 'ClaimedCapability', schema: schemas.ClaimedCapabilitySchema },
  { type: 'LatencyClaim', schema: schemas.LatencyClaimSchema },
  { type: 'CostClaim', schema: schemas.CostClaimSchema },
  { type: 'CandidateProvenance', schema: schemas.CandidateProvenanceSchema },
  { type: 'CandidateSecurity', schema: schemas.CandidateSecuritySchema },
  { type: 'CandidateProfile', schema: schemas.CandidateProfileSchema },
  { type: 'HumanDeclaration', schema: schemas.HumanDeclarationSchema },
  { type: 'CandidateMatch', schema: schemas.CandidateMatchSchema },
  { type: 'CandidateAssignment', schema: schemas.CandidateAssignmentSchema },
  { type: 'RoleResolution', schema: schemas.RoleResolutionSchema },
  { type: 'GapTransition', schema: schemas.GapTransitionSchema },
  { type: 'CapabilityGap', schema: schemas.CapabilityGapSchema },
  { type: 'EcosystemDiscoveryRequest', schema: schemas.EcosystemDiscoveryRequestSchema },
  { type: 'OrganizationRoleBinding', schema: schemas.OrganizationRoleBindingSchema },
  { type: 'HandoffEdge', schema: schemas.HandoffEdgeSchema },
  { type: 'SupervisionEdge', schema: schemas.SupervisionEdgeSchema },
  { type: 'OrganizationEstimates', schema: schemas.OrganizationEstimatesSchema },
  { type: 'OrganizationProposal', schema: schemas.OrganizationProposalSchema },
  { type: 'EvaluationCriterion', schema: schemas.EvaluationCriterionSchema },
  { type: 'CriterionResult', schema: schemas.CriterionResultSchema },
  { type: 'OrganizationEvaluation', schema: schemas.OrganizationEvaluationSchema },
  { type: 'OrganizationSelection', schema: schemas.OrganizationSelectionSchema },
  { type: 'DiscoveryStageLink', schema: schemas.DiscoveryStageLinkSchema },
  { type: 'DiscoveryRunTrigger', schema: schemas.DiscoveryRunTriggerSchema },
  { type: 'DiscoveryRun', schema: schemas.DiscoveryRunSchema },
  { type: 'DiscoveryRunArtifact', schema: schemas.DiscoveryRunArtifactSchema },
  { type: 'SourceArtifact', schema: schemas.SourceArtifactSchema },
  { type: 'SourceScanQuery', schema: schemas.SourceScanQuerySchema },
  { type: 'SourceScanResult', schema: schemas.SourceScanResultSchema },
  { type: 'SandboxReport', schema: schemas.SandboxReportSchema },
  { type: 'CandidateEvaluationEvidence', schema: schemas.CandidateEvaluationEvidenceSchema },
  { type: 'PolicyApproval', schema: schemas.PolicyApprovalSchema },
  { type: 'PromotionRecord', schema: schemas.PromotionRecordSchema },
  { type: 'EcosystemScanReport', schema: schemas.EcosystemScanReportSchema },
  { type: 'EcosystemProposalEvidence', schema: schemas.EcosystemProposalEvidenceSchema },
  { type: 'DomainPackProposalDetail', schema: schemas.DomainPackProposalDetailSchema },
  { type: 'EcosystemProposal', schema: schemas.EcosystemProposalSchema },
  { type: 'DiscoverySchedule', schema: schemas.DiscoveryScheduleSchema },
  { type: 'DueDiscoveryRun', schema: schemas.DueDiscoveryRunSchema },
  { type: 'DiscoveryIssue', schema: schemas.DiscoveryIssueSchema },
  { type: 'DiscoveryError', schema: schemas.DiscoveryErrorSchema },
];
